version: '3.8'

services:
  backend:
    build:
      context: ./Backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./Frontend
    container_name: streamlit-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
